baseurl = "https://dhersz.netlify.app/"
title = "Daniel Herszenhut"
author = "Daniel Herszenhut"
canonifyurls = true
paginate = 3
theme = "hugo-renga"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
DefaultContentLanguage = "pt"
defaultContentLanguageInSubdir = true

# googleAnalytics = "UA-00000000-1"
# disqusShortname = "your-disqus-shortname"

[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
  pagetitle = "Daniel Herszenhut"
  copyright = "© 2020 Daniel Herszenhut"
  copyrightUrl = "https://dhersz.netlify.app/"
  faviconfile = "image/favicon.png"
  logofile = "image/avatar.png"
  posts_navigation = true
  uselatex = true
  highlightjs = true
  progressively = false
  github = "dhersz"
  twitter = "dhersz"
  email = "dhersz@gmail.com"

[languages.en]
  languageCode = "en"
  # languageName = "English"

[[languages.en.menu.primary]]
  identifier = "about"
  name = "About"
  url = "/en/about/"
  weight = 1

[[languages.en.menu.primary]]
  identifier = "blog"
  name = "Blog"
  url = "/en/blog/"
  weight = 2

[languages.pt]
  languageCode = "pt"
  # languageName = "Português"

[[languages.pt.menu.primary]]
  identifier = "sobre"
  name = "Sobre"
  url = "/pt/about/"
  weight = 1

[[languages.pt.menu.primary]]
  identifier = "blog"
  name = "Blog"
  url = "/pt/blog/"
  weight = 2
