baseurl = "https://dhersz.netlify.app/"
title = "Daniel Herszenhut"
author = "Daniel Herszenhut"
canonifyurls = true
languagecode = "en"
paginate = 3
theme = "hugo-renga"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# googleAnalytics = "UA-00000000-1"
# disqusShortname = "your-disqus-shortname"

[permalinks]
post = "/:year/:month/:day/:slug/"

[params]
pagetitle = "Daniel Herszenhut"
copyright = "© 2020 Daniel Herszenhut"
copyrightUrl = "https://dhersz.netlify.app/"
faviconfile = "image/favicon.png"
logofile = "image/avatar.png"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "dhersz"
twitter = "dhersz"
email = "dhersz@gmail.com"

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2
