baseurl = "https://dhersz.netlify.app/"
title = "Daniel Herszenhut"
author = "Daniel Herszenhut"
canonifyurls = true
paginate = 3
theme = "hugo-nanx2020"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
DefaultContentLanguage = "pt"
defaultContentLanguageInSubdir = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
  pagetitle = "Daniel Herszenhut"
  copyright = "© 2021 Daniel Herszenhut"
  faviconfile = "image/favicon.png"
  logofile = "image/avatar.jpg"
  posts_navigation = true
  uselatex = true
  highlightjs = true
  highlightjslanguages = ["r"]
  progressively = false
  github = "dhersz"
  twitter = "dhersz"
  contact = "dhersz@gmail.com"

[languages.en]
  languageCode = "en"
  # languageName = "English"

[[languages.en.menu.primary]]
  identifier = "blog"
  name = "Blog"
  url = "/en/blog/"
  weight = 1

[[languages.en.menu.primary]]
  identifier = "projects"
  name = "Projects"
  url = "/en/projects/"
  weight = 2

[[languages.en.menu.primary]]
  identifier = "publications"
  name = "Publications"
  url = "/en/publications/"
  weight = 3

[languages.pt]
  languageCode = "pt"
  # languageName = "Português"

[[languages.pt.menu.primary]]
  identifier = "blog"
  name = "Blog"
  url = "/pt/blog/"
  weight = 1

[[languages.pt.menu.primary]]
  identifier = "projetos"
  name = "Projetos"
  url = "/pt/projects/"
  weight = 2

[[languages.pt.menu.primary]]
  identifier = "publicacoes"
  name = "Publicações"
  url = "/pt/publications/"
  weight = 3
