---
title: Faz um site, vai...
author: Daniel Herszenhut
date: '2020-11-28'
slug: faz-um-site
categories: []
tags: []
meta_img: images/site-home.png
description: Vai ser tranquilo...
---

Depois de criar vários blogs e sites ao longo de alguns anos na internet, finalmente estou criando um site para guardar e chamar de meu. Até então quase sempre criava essas páginas no intuito de postar algum desabafo ou então com uma mentalidade de me comprometer como o comunicador de algo (um projeto, uma ideia, qualquer coisa assim), o que acabava implicando em certos "deveres" auto impostos e levava a uma desmotivação generalizada.

Dessa vez resolvi fazer diferente. Depois de ler o post [Reimaginando o PhD](https://nadiaeghbal.com/phd) (em inglês), da Nadia Eghbal, fiquei sentindo que precisava ter uma página pra divulgar o meu trabalho. Mais do que um canal de comunicação com publicações frequentes, portanto, a ideia desse site é ser um "cartão de visitas" àqueles que quiserem conhecer um pouco da minha produção profissional. E, de quebra, de funcionar também como um repositório de ideias e pensamentos que esteja sentindo vontade de publicar, como esse post.

Pra criar o site usei o pacote de R [`blogdown`](https://github.com/rstudio/blogdown/) seguindo as instruções do seu ótimo [livro-documentação](https://bookdown.org/yihui/blogdown/). Dei uma empacada no que talvez fosse a parte mais simples, de escolher o tema pra página, mas demorei a achar um que me agradasse. Tinha como referências estéticas o próprio site da [Nadia Eghbal](https://nadiaeghbal.com) e o do [Nan Xiao](https://nanx.me/), mas queria também algumas funcionalidades do [tema acadêmico do Hugo](https://themes.gohugo.io/academic/). Acabei decidindo usar O [Renga](https://github.com/nanxstats/hugo-renga), do Nan Xiao, mas customizei ele tanto que na verdade ele agora mais parece o [nanx2020](https://github.com/nanxstats/hugo-nanx2020/). Minha ideia também é adicionar uma página relativa à cada publicação minha, na linha do que faz o [Urban Demographics](https://www.urbandemographics.org) ([exemplo](https://www.urbandemographics.org/publication/2020_naturehb_covid19/)), mas tive alguns problemas fazendo isso e acabei deixando de lado, por ora.

O processo todo foi simples, mas como queria algo mais com a minha cara e com umas funcionalidades extras acabei me estressando e gastando muito mais tempo do que gostaria. Por exemplo, algumas páginas são bilingues (português/inglês), então tive que aprender a habilitar essa função (não foi lá muito difícil, pra ser honesto, mas enfim). Fiquei muito tempo (muito tempo) tentando tentando deixar os blocos de código bonitos, até entender qual parâmetro eu precisava mexer e que outra parte do problema era resolvida usando arquivos `.Rmd` em vez de `.md` pra escrever os posts. Enfim, aprendizados. Foi simples mas não ridículo.

A ideia é não deixar isso completamente às moscas, agora. Não prometo posts semanais ou mensais (não sei para quem eu estaria prometendo isso, é verdade), mas no mínimo vou manter a página de publicações (soon^TM^) e de projetos atualizadas.

Até mais!
